annotations:
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/startechnica/apps/tree/main/charts/freeradius
    - name: Upstream Project
      url: https://github.com/FreeRADIUS/freeradius-server
  category: AccessManagement
apiVersion: v2
appVersion: 3.0.26
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 11.x.x
description: FreeRADIUS is a modular, high performance free RADIUS suite developed
  and distributed under the GNU General Public License, version 2, and is free for
  download and use.
home: https://github.com/startechnica/apps/tree/main/charts/freeradius
icon: https://freeradius.org/img/wordmark.svg
keywords:
- freeradius
- radius
- mysql
- postgresql
- ldap
kubeVersion: '>=1.16.0-0'
maintainers:
- email: firmansyah@nainggolan.id
  name: Firmansyah Nainggolan
  url: https://firmansyah.nainggolan.id
name: freeradius
sources:
- https://freeradius.org/
type: application
version: 0.1.5
