apiVersion: v2
name: convertdata
description: A Helm chart for Convert_data app

dependencies:
  - name: common
    repository: https://svtechnmaa.github.io/charts/artifacthub/
    version: x.x.x

version: 0.6.1
appVersion: "v1.0.0"