{{- $basePath := .Values.global.basePath }}
{{- $namespace := .Release.Namespace }}

apiVersion: v1
kind: PersistentVolume
metadata:
  # name: "rest-converter-logs"
  name: "{{ $namespace }}-airflow-logs-pv" 
  labels:
    tier: airflow
    component: logs-pvc
    release: {{ .Release.Name }}
    

spec:
  storageClassName: {{ $namespace }}-airflow-logs-hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ $basePath }}/{{ $namespace }}/airflow_logs