# {{- if .Values.global.airflow.dags.persistence.enabled }}
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: rest-converter-dags
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: "rest-converter-dags"
#   labels:
#     tier: airflow
#     component: dags-pvc
#     release: {{ .Release.Name }}
    

# spec:
#   storageClassName: rest-converter-dags
#   capacity:
#     storage: {{ .Values.global.airflow.dags.persistence.size | quote }}
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: /opt/shared/default/repo_automation/airflow/


# {{- end }}