apiVersion: v1
kind: ConfigMap
metadata:
  name: juniper-syslog-api
data:
  conf.yaml: |
    ES:
      url: https://master-es-http:9200
      username: elastic
      passwd: juniper@123
    LOG_TAGS:
      link down:
        operator: AND
        events:
        - field: junos_eventname
          value: SNMP_TRAP_LINK_DOWN
          junos_procsname: mib2d
          junos_severitycode: 4
          operation: "="
        - field: junos_eventname
          value: BFDD_STATE_UP_TO_DOWN
          junos_procsname: bfdd
          junos_severitycode: 4
          operation: "="
        - field: junos_eventname
          value: BFDD_TRAP_SHOP_STATE_DOWN
          junos_procsname: bfdd
          junos_severitycode: 4
          operation: "="
      interface down:
        operator: AND
        events:
        - field: junos_eventname
          value: SNMP_TRAP_LINK_DOWN
          junos_procsname: mib2d
          junos_severitycode: 4
          operation: "="
        - field: junos_eventname
          value: RPD_LDP_NBRDOWN
          junos_procsname: rpd
          junos_severitycode: 5
          operation: "="
        - field: junos_eventname
          value: RPD_OSPF_NBRDOWN
          junos_procsname: rpd
          junos_severitycode: 5
          operation: "="
      OSPF down:
        operator: AND
        events:
        - field: junos_eventname
          value: RPD_OSPF_NBRDOWN
          junos_procsname: rpd
          junos_severitycode: 5
          operation: "="
      LDP down:
        operator: OR
        events:
        - field: junos_eventname
          value: RPD_LDP_NBRDOWN
          junos_procsname: rpd
          junos_severitycode: 5
          operation: "="
        - field: junos_eventname
          value: RPD_LDP_SESSIONDOWN
          junos_procsname: rpd
          junos_severitycode: 5
          operation: "="
      BGP down:
        operator: OR
        events:
        - field: junos_msg
          value: bgp_bfd_callback
          junos_procsname: rpd
          junos_severitycode: 4
          operation: "~"
        - field: junos_eventname
          value: BGP_NLRI_MISMATCH
          junos_procsname: rpd
          junos_severitycode: 4
          operation: "="
        - field: junos_eventname
          value: BGP_IO_ERROR_CLOSE_SESSION
          junos_procsname: rpd
          junos_severitycode: 4
          operation: "="
    LIST_FIELDS:
    - junos_procsname
    - junos_msg
    - junos_eventname
    - junos_hostname
    - '@timestamp'
    - junos_severityname
    - junos_facilityname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: juniper-syslog-api
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ include "common.replicas" ( dict "replicaCount" .Values.replicaCount "global" .Values.global ) }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: juniper-syslog-api
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: juniper-syslog-api
    spec:
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: juniper-syslog-api
        image: {{ include "common.images.image" ( dict "imageRoot" .Values.image "global" .Values.global ) }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: main
          containerPort: 8502
        volumeMounts:
        - name: config-volume
          mountPath: /juniper_syslog_api/syslog_dashboard/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: config-volume
        configMap:
          name: juniper-syslog-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.global.externalIP }}
  externalIPs:
    - {{ .Values.global.externalIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: main
      port: {{ .Values.service.port }}
      targetPort: main
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}

  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
