apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Namespace }}-ingress-nginx
    app.kubernetes.io/part-of: {{ .Release.Namespace }}-ingress-nginx
spec:
  controller: k8s.io/ingress-nginx
