---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Namespace }}-ingress-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Namespace }}-ingress-nginx
    app.kubernetes.io/part-of: {{ .Release.Namespace }}-ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}-ingress-nginx
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Namespace }}-ingress-nginx
    namespace: {{ .Release.Namespace }}
