apiVersion: v1
kind: Secret
metadata:
  name: tls
type: kubernetes.io/tls
data:
  tls.key:
{{- include "ingress-nginx.tls.key" . | b64enc | indent 1 }}
  tls.crt:
{{- include "ingress-nginx.tls.cert" . | b64enc | indent 1 }}
