global:
  imageRegistry: ghcr.io/moophat
  basePath: /opt/shared

databaseConfig:
  host: mariadb
  port: 3306
  user: tacgui
  password: juniper@123
  databaseName: tgui
  logDatabaseName: tgui_log

image:
  repository: svtechnmaa/svtech_tacacsgui
  tag: v1.0.0
  pullPolicy: IfNotPresent
