---
{{- $basePath := .Values.global.basePath }}
{{- $namespace := .Release.Namespace }}

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ $namespace }}-tacgui-config-pv"
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ $namespace }}-tacgui-config-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ $basePath }}/{{ $namespace }}/tacgui-config

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ $namespace }}-tacgui-backups-pv"
  annotations:
    helm.sh/resource-policy: keep
spec:
  storageClassName: {{ $namespace }}-tacgui-backups-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ $basePath }}/{{ $namespace }}/tacgui-backups
