freeradius:
  enabled: true
  replicaCount: 3
  service:
    type: LoadBalancer
    loadBalancerIP: "10.98.13.4"
    externalTrafficPolicy: Local
  command: []
    # - "/bin/sh"
    # - "-c"
    # - "tail -f /dev/null"
  args: []
    # - "-xX"
  modsEnabled:
    sql:
      enabled: true
    dynamicClients:
      enabled: true
  sitesEnabled:
    coa:
      enabled: false
      listen: "*"
    status:
      enabled: true
      listen: 127.0.0.1
      secret: adminsecret
    dynamicClients:
      enabled: true
  mariadb:
    enabled: true
    auth:
      username: radius
      password: "juniper@123"
      database: radius
      existingSecret: ""
    architecture: standalone
    initdbScriptsConfigMap: "sample-raddb"
  externalDatabase:
    host: "radius-mariadb"
    port: 3306
    user: radius
    database: radius
    password: "juniper@123"

daloradius:
  enabled: true
  service:
    type: LoadBalancer
    loadBalancerIP: "10.98.13.5"
  externalDatabase:
    host: "radius-mariadb"
    port: 3306
    user: radius
    database: radius
    password: "juniper@123"
    existingSecret: ""
    existingSecretPasswordKey: ""
