apiVersion: v2
annotations:
  category: Proxy
name: proxy
description: SVTECH Proxy
engine: gotpl

dependencies:
  - name: common
    repository: https://moophat.github.io/SVTECH_Public_Helmchart/artifacthub/
    version: 1.x.x

version: 1.0.0
appVersion: "v1.0.0"
