global:
  sharedVolume:
    enabled: true
  redis:
    enabled: true
  icingadb:
    enabled: true
  sharedPersistenceVolume:
    - volumeName: automation-repo-volume
      pvcName: automation-repo-pvc
      storageSize: 2Gi
      path: /opt/SVTECH-Junos-Automation
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - preparation
        - rundeck
        - rundeck-option-provider
        - debuger
        - csv-view
        - init-data-grafana
        - icinga2
        - icinga2-satellite
      storageClass: automation-repo-hostpath

    - volumeName: icinga2-zones-volume
      pvcName: icinga2-zones-pvc
      storageSize: 2Gi
      path: /etc/icinga2/zones.d
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icinga2
        - rundeck
        - rundeck-option-provider
        - debuger
      storageClass: icinga2-zones-hostpath

    - volumeName: icinga2-conf-volume
      pvcName: icinga2-conf-pvc
      storageSize: 100Mi
      path: /etc/icinga2/conf.d
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icinga2
        - debuger
      storageClass: icinga2-conf-hostpath

    # - volumeName: icinga2-scripts-volume
    #   pvcName: icinga2-scripts-pvc
    #   storageSize: 100Mi
    #   path: /etc/icinga2/scripts
    #   accessModes: ReadWriteOnce #ReadWriteMany
    #   shareFor:
    #     - preparation
    #     - icinga2
    #     - debuger

    - volumeName: icinga2-plugins-volume
      pvcName: icinga2-plugins-pvc
      storageSize: 2Gi
      path: /usr/share/icinga2/plugins/libexec
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icinga2
        - debuger
        - icinga2-satellite
      storageClass: icinga2-plugins-hostpath

    # - volumeName: icinga2-output-volume
    #   pvcName: icinga2-output-pvc
    #   storageSize: 3Gi
    #   path: /var/tmp/output/
    #   accessModes: ReadWriteOnce #ReadWriteMany
    #   shareFor:
    #     - icinga2
    #     - debuger

    - volumeName: gitlist-data-volume
      pvcName: gitlist-data-pvc
      storageSize: 2Gi
      path: /opt/gitlist
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - gitlist
        - rundeck
        - debuger
      storageClass: gitlist-data-hostpath

    - volumeName: nagvis-maps-volume
      pvcName: nagvis-maps-pvc
      storageSize: 2Gi
      path: /usr/share/nagvis/etc/maps
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - nagvis
        - rundeck
        - debuger
      storageClass: nagvis-maps-hostpath

    - volumeName: rundeck-var-volume
      pvcName: rundeck-var-pvc
      storageSize: 10Gi
      path: /home/rundeck/var
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - debuger
      storageClass: rundeck-var-hostpath

    - volumeName: nagvis-auth-db-volume
      pvcName: nagvis-auth-db-pvc
      storageSize: 1Gi
      path: /usr/share/nagvis/etc
      subPath: auth.db
      accessModes: ReadWriteOnce
      shareFor:
        - nagvis
        - rundeck
      storageClass: nagvis-auth-db-hostpath

    - volumeName: rundeck-project-volume
      pvcName: rundeck-project-pvc
      storageSize: 1Gi
      path: /home/rundeck/projects
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - debuger
      storageClass: rundeck-project-hostpath

    - volumeName: rundeck-jsnapy-volume
      pvcName: rundeck-jsnapy-pvc
      storageSize: 10Gi
      path: /var/lib/rundeck/jsnapy
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - rundeck-option-provider
        - debuger
      storageClass: rundeck-jsnapy-hostpath

    - volumeName: rundeck-backup-volume
      pvcName: rundeck-backup-pvc
      storageSize: 10Gi
      path: /opt/backup
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - debuger
      storageClass: rundeck-backup-hostpath

    - volumeName: csv-output-volume
      pvcName: csv-output-pvc
      storageSize: 10Gi
      path: /opt/csv-output
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - csv-view
        - debuger
      storageClass: csv-output-hostpath

    - volumeName: thruk-volume
      pvcName: thruk-pvc
      storageSize: 30Mi
      path: /etc/thruk
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - thruk
        - rundeck
      storageClass: thruk-hostpath

    - volumeName: icingaweb-volume
      pvcName: icingaweb-pvc
      storageSize: 10Mi
      path: /data
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icingaweb
      storageClass: icingaweb-hostpath
    
    # snmp-manager volume
    - volumeName: snmp-manager-volume
      pvcName: snmp-manager-pvc
      storageSize: 10Mi
      path: /etc/snmptt/
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - snmp-manager
      storageClass: snmp-manager-hostpath
  database:
    director:
      enabled: true
      database: directordb
      username:
      password:
      # host: mariadb
      # port: 3306
    icingadb:
      enabled: true
      database: icingadb
      username:
      password:
      # host: mariadb
      # port: 3306
    icingaweb2:
      enabled: true
      database: icingaweb2db
      username:
      password:
      # host: mariadb
      # port: 3306
    snmptt:
      enabled: false
      database: snmptt
      username:
      password:
      # host: mariadb
      # port: 3306
      # unknownTable: snmptt_unknown
  api:
    port: 5665
    user: icingaAdmin
    password: icingaAdmin


timezone: Asia/Ho_Chi_Minh


init:
  image:
    registry: docker.io
    repository: busybox
    tag: "1.33"
    pullPolicy: IfNotPresent
image:
  repository: svtechnmaa/svtech_icingaweb2
  tag: v1.0.2
  pullPolicy: IfNotPresent
  debug: false
containerPort:
  icingaweb: 8080
# Icingaweb authentication variables
auth:
  type: db
  #resource: # Add the name of the db resource used by Icinga Web 2 here. Default: Values.global.database.icingaweb2.database
  admin_user: icingaweb
  admin_password: juniper@123
# Icingaweb module variables
modules:
  director:
    enabled: true
    kickstart: true
  icingadb:
    enabled: true
  incubator:
    enabled: true
  grafana:
    enabled: true
    default_dashboard: icinga2-default
    default_dashboard_uid: icinga2-default
    default_dashboard_panelid: "1"
env:
  TZ: Asia/Ho_Chi_Minh

clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}

replicaCount: 2

persistence:
  enabled: true
  storageClass: "icingaweb"
  accessModes:
    - ReadWriteOnce
  size: 10Mi
  # mountPath on Container
  mountPath: /data
  # hostPath: mount path on Host
  hostPath: icingaweb_conf # full path: {{ $basePath }}/{{ $namespace }}/{{ $hostPath }}. Eg: /opt/shared/default/icingaweb_config

updateStrategy: RollingUpdate
podManagementPolicy: OrderedReady
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []


## Affinity for pod assignment
## Note: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
##
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: icingaweb
          # app.kubernetes.io/instance: nms
          app.kubernetes.io/name: icingaweb
      topologyKey: app.kubernetes.io/hostname

## Node labels for pod assignment
nodeSelector: {}

## Tolerations for pod assignment
tolerations: []

## Extra volumes to add to the deployment
extraVolumes: []

## Extra volume mounts to add to the container
extraVolumeMounts: []

securityContext:
  enabled: true
  runAsGroup: 33
  runAsUser: 33

resources:
  limits: {}
  #   cpu: 100m
  #   memory: 128Mi
  requests: {}
  #   cpu: 100m
  #   memory: 128Mi


livenessProbe:
  enabled: false
  initialDelaySeconds: 180
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6
readinessProbe:
  enabled: false
  initialDelaySeconds: 60
  periodSeconds: 45
  timeoutSeconds: 30
  successThreshold: 1
  failureThreshold: 6

## Custom Liveness probe
customLivenessProbe: {}

## Custom Readiness probe
customReadinessProbe: {}

## Container ports
containerPorts:
  # icinga2Api: 5665
  # livestatus: 6558


service:
  ## Service type
  ##
  type: ClusterIP
  port: 8080

  # loadBalancerIP:
  # loadBalancerSourceRanges:
  # - 10.10.10.0/24

  # externalIPs: ["10.98.0.143"]

  ## Set the Cluster IP to use
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#choosing-your-own-ip-address
  ##
  # clusterIP: None
  ## Provide any additional annotations which may be required
  ##
  annotations: {}
  ## Set the service SessionAffinity for session stickiness
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace
  sessionAffinity: ClientIP

  # ## Customize the SessionAffinity configuration. The default value for sessionAffinityConfig.clientIP.timeoutSeconds is 10800 (3 hours)
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 7200
