apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  user: {{ .Values.global.github.user | b64enc | quote }}
  token: {{ .Values.global.github.token | b64enc | quote }}
  fg_token: {{ .Values.global.github.fg_token | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-gpgkey
type: Opaque
data:
  private_key.asc: {{ .Values.global.github.gpgkey | b64enc | quote }}
