{{- if .Values.workers.persistence.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rest-converter-worker
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

{{- range $index, $topping := until (int .Values.workers.replicas) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "rest-converter-worker-{{ $index }}"
  labels:
    tier: airflow
    component: worker
    release: {{ $.Release.Name }}
spec:
  storageClassName: rest-converter-worker
  capacity:
    storage: {{ $.Values.workers.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/rest_converter_worker

{{- end }}
{{- end }}