# icingaweb apache configmap - get data from _icingaweb-apache.tpl
apiVersion: v1
kind: ConfigMap
metadata:
  name: icingaweb-http
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: icingaweb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  icingaweb2.conf: |-
{{- include "icingaweb.icingaweb.apache" . | indent 4 }}
