---
# SA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: icinga-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: icinga-exec-role
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "list", "create"]  # Permissions needed to exec commands in pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: icinga-exec-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: icinga-exec-role
subjects:
  - kind: ServiceAccount
    name: icinga-sa
    namespace: {{ .Release.Namespace }}
