# Default values for snmp-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  database:
    director:
      enabled: true
      database: directordb
      username:
      password:
      # host: mariadb
      # port: 3306
    icingadb:
      enabled: true
      database: icingadb
      username:
      password:
      # host: mariadb
      # port: 3306
    icingaweb2:
      enabled: true
      database: icingaweb2db
      username:
      password:
      # host: mariadb
      # port: 3306
    snmptt:
      enabled: false
      database: snmptt
      username:
      password:
      # host: mariadb
      # port: 3306
      # unknownTable: snmptt_unknown
  # Icinga2 api connection
  api:
    # host:  # only needed if Icinga2 runs out of cluster
    port: 5665
    user: icingaAdmin
    password: icingaAdmin
  sharedVolume:
    enabled: true
  sharedPersistenceVolume:
    - volumeName: automation-repo-volume
      pvcName: automation-repo-pvc
      storageSize: 2Gi
      path: /opt/SVTECH-Junos-Automation
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - preparation
        - rundeck
        - rundeck-option-provider
        - debuger
        - csv-view
        - init-data-grafana
        - icinga2
        - icinga2-satellite
      storageClass: automation-repo-hostpath

    - volumeName: icinga2-zones-volume
      pvcName: icinga2-zones-pvc
      storageSize: 2Gi
      path: /etc/icinga2/zones.d
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icinga2
        - rundeck
        - rundeck-option-provider
        - debuger
      storageClass: icinga2-zones-hostpath

    - volumeName: icinga2-conf-volume
      pvcName: icinga2-conf-pvc
      storageSize: 100Mi
      path: /etc/icinga2/conf.d
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icinga2
        - debuger
      storageClass: icinga2-conf-hostpath

    # - volumeName: icinga2-scripts-volume
    #   pvcName: icinga2-scripts-pvc
    #   storageSize: 100Mi
    #   path: /etc/icinga2/scripts
    #   accessModes: ReadWriteOnce #ReadWriteMany
    #   shareFor:
    #     - preparation
    #     - icinga2
    #     - debuger

    - volumeName: icinga2-plugins-volume
      pvcName: icinga2-plugins-pvc
      storageSize: 2Gi
      path: /usr/share/icinga2/plugins/libexec
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icinga2
        - debuger
        - icinga2-satellite
      storageClass: icinga2-plugins-hostpath

    # - volumeName: icinga2-output-volume
    #   pvcName: icinga2-output-pvc
    #   storageSize: 3Gi
    #   path: /var/tmp/output/
    #   accessModes: ReadWriteOnce #ReadWriteMany
    #   shareFor:
    #     - icinga2
    #     - debuger

    - volumeName: gitlist-data-volume
      pvcName: gitlist-data-pvc
      storageSize: 2Gi
      path: /opt/gitlist
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - gitlist
        - rundeck
        - debuger
      storageClass: gitlist-data-hostpath

    - volumeName: nagvis-maps-volume
      pvcName: nagvis-maps-pvc
      storageSize: 2Gi
      path: /usr/share/nagvis/etc/maps
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - nagvis
        - rundeck
        - debuger
      storageClass: nagvis-maps-hostpath

    - volumeName: rundeck-var-volume
      pvcName: rundeck-var-pvc
      storageSize: 10Gi
      path: /home/rundeck/var
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - debuger
      storageClass: rundeck-var-hostpath

    - volumeName: nagvis-auth-db-volume
      pvcName: nagvis-auth-db-pvc
      storageSize: 1Gi
      path: /usr/share/nagvis/etc
      subPath: auth.db
      accessModes: ReadWriteOnce
      shareFor:
        - nagvis
        - rundeck
      storageClass: nagvis-auth-db-hostpath

    - volumeName: rundeck-project-volume
      pvcName: rundeck-project-pvc
      storageSize: 1Gi
      path: /home/rundeck/projects
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - debuger
      storageClass: rundeck-project-hostpath

    - volumeName: rundeck-jsnapy-volume
      pvcName: rundeck-jsnapy-pvc
      storageSize: 10Gi
      path: /var/lib/rundeck/jsnapy
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - rundeck-option-provider
        - debuger
      storageClass: rundeck-jsnapy-hostpath

    - volumeName: rundeck-backup-volume
      pvcName: rundeck-backup-pvc
      storageSize: 10Gi
      path: /opt/backup
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - debuger
      storageClass: rundeck-backup-hostpath

    - volumeName: csv-output-volume
      pvcName: csv-output-pvc
      storageSize: 10Gi
      path: /opt/csv-output
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - rundeck
        - csv-view
        - debuger
      storageClass: csv-output-hostpath

    - volumeName: thruk-volume
      pvcName: thruk-pvc
      storageSize: 30Mi
      path: /etc/thruk
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - thruk
        - rundeck
      storageClass: thruk-hostpath

    - volumeName: icingaweb-volume
      pvcName: icingaweb-pvc
      storageSize: 10Mi
      path: /data
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - icingaweb
      storageClass: icingaweb-hostpath

    # snmp-manager volume
    - volumeName: snmp-manager-volume
      pvcName: snmp-manager-pvc
      storageSize: 10Mi
      path: /etc/snmptt/
      accessModes: ReadWriteOnce #ReadWriteMany
      shareFor:
        - snmp-manager
      storageClass: snmp-manager-hostpath
clusterDomain: cluster.local

image:
  repository: svtechnmaa/svtech_snmp_manager
  tag: v1.0.1
  pullPolicy: IfNotPresent
  debug: false
containerPort:
  snmp-manager: 162
env:
  TZ: Asia/Ho_Chi_Minh
  # Set the environment variable to enable logging events to the database. 1: enable, 0: disable
  MYSQL_DBI_ENABLE: "1"
service:
  type: ClusterIP
  # Uncomment this if you want to use LoadBalancer. Change the ip address to your own IP
  # loadBalancerIP: 10.98.6.17
  port: 162
  protocol: UDP
  # nodePort: 30162 # comment this if you want to use LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  ## Customize the SessionAffinity configuration. The default value for sessionAffinityConfig.clientIP.timeoutSeconds is 10800 (3 hours)
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 7200
replicaCount: 2
persistence:
  enabled: true
  storageClass: "snmp-manager"
  accessModes:
    - ReadWriteOnce
  size: 10Mi
  # mountPath on Container
  mountPath: /etc/snmptt/
  # hostPath: mount path on Host
  hostPath: snmp-manager-conf # full path: {{ $basePath }}/{{ $namespace }}/{{ $hostPath }}. Eg: /opt/shared/default/snmp-manager-config
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: snmp-manager
          # app.kubernetes.io/instance: nms
          app.kubernetes.io/name: snmp-manager
      topologyKey: app.kubernetes.io/hostname

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  enabled: false
  runAsGroup: 1000
  runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []


